### ISSUE TITLE
execution fails 

### ISSUE THREAD

**Issue by BaptisteCecconi** [maserlib/maser4py#20]
I have an execution error, when using `master` or `develop` on the Nançay das2server. 
It is related to `maser/services/helio/hfc/hfcviewer.py`, although I don't use it:
```
Traceback (most recent call last):
  File "/usr/local/bin/das2rdr/das2nancay/das2_maser_nda_routine.py", line 11, in <module>
    from  maser.data.nancay.nda import routine
  File "/usr/local/lib/python3.5/dist-packages/maser4py-0.8.2-py3.5.egg/maser/__init__.py", line 4, in <module>
    from maser.script import main
  File "/usr/local/lib/python3.5/dist-packages/maser4py-0.8.2-py3.5.egg/maser/script.py", line 22, in <module>
    from maser.services.helio.hfc import hfcviewer, add_hfcviewer_subparser
  File "/usr/local/lib/python3.5/dist-packages/maser4py-0.8.2-py3.5.egg/maser/services/helio/hfc/__init__.py", line 2, in <module>
    from maser.services.helio.hfc.subparser import add_hfcviewer_subparser
  File "/usr/local/lib/python3.5/dist-packages/maser4py-0.8.2-py3.5.egg/maser/services/helio/hfc/subparser.py", line 8, in <module>
    from maser.services.helio.hfc.hfcviewer import DATE, OBSERVATORY, INSTRUMENT, TELESCOPE, WAVENAME, URL_WSDL
  File "/usr/local/lib/python3.5/dist-packages/maser4py-0.8.2-py3.5.egg/maser/services/helio/hfc/hfcviewer.py", line 19, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
ImportError: cannot import name 'NavigationToolbar2Tk'
```
If I replace 
```
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
```
by
```
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg
```
in `maser/services/helio/hfc/hfcviewer.py`, the error disappears. I didn't check if `hfcviewer.py` is broken after this, but I can use maser4py here.

**Comment by xbonnin** [comment]
hfcviewer.py has been removed from maser4py.
I think we can close the issue.
